export const aspData = {
  team: {
    name: "ASP Study Hub",
    org: "team-ASP",
    githubOrgUrl: "https://github.com/team-ASP",
    season: "2026 운영 전환",
    mission:
      "스터디와 프로젝트의 계획, 진행 기록, 실험 결과, 발표 자료, 회고를 한 곳에 모아 팀 지식으로 남긴다.",
  },
  members: [
    {
      id: "project-maintainer",
      name: "Project Maintainer",
      github: "team-ASP",
      role: "Developer",
      focus: "프로젝트 계획, 리뷰, 아카이브 승인",
      siteRole: "developer",
    },
    {
      id: "study-editor",
      name: "Study Editor",
      github: "team-ASP-member",
      role: "Developer",
      focus: "세션 기록, 실험 로그, 태스크 업데이트",
      siteRole: "developer",
    },
    {
      id: "admin",
      name: "Bu-seung So",
      github: "bootkorea",
      role: "Admin",
      focus: "권한, 배포, 보안, 감사 로그",
      siteRole: "admin",
    },
  ],
  projects: [
    {
      id: "mafia-simulation",
      title: "Multi-Agent Mafia Simulation",
      type: "research",
      status: "planning",
      period: { start: "2026-06-15", end: "2026-09-06" },
      repositoryUrl: "https://github.com/team-ASP/MafiaSimulation",
      demoUrl: "",
      presentationUrl: "",
      ownerId: "project-maintainer",
      memberIds: ["project-maintainer", "study-editor"],
      summary:
        "Unity 환경에서 LLM 기반 에이전트들이 마피아 게임을 수행하며 기억, 대화, 투표, 거짓말, 사회적 추론 행동을 관찰하는 12주 연구 프로젝트.",
      goals: [
        "6명 이상 에이전트가 낮, 회의, 투표, 밤 처형 사이클을 완주한다.",
        "OpenAI, Claude, DeepSeek, Ollama 등 provider별 응답 안정성과 행동 차이를 비교한다.",
        "게임 로그, 실험 결과, 발표 자료, 회고를 공개 아카이브로 정리한다.",
      ],
      successCriteria: [
        "day/meeting/voting/night cycle이 3회 이상 중단 없이 진행된다.",
        "JSON parse 실패율, latency, 행동 품질을 실험 로그로 비교한다.",
        "최종 발표에 demo 영상, architecture diagram, 실험 결과표, 후속 과제가 포함된다.",
      ],
      risks: [
        {
          title: "LLM 응답 형식 불안정",
          impact: "투표와 대화 루프가 중단될 수 있음",
          mitigation: "JsonFixer, retry policy, provider별 response validation을 실험한다.",
          status: "watching",
        },
        {
          title: "실험 재현성 부족",
          impact: "모델 행동 비교가 주관적으로 흐를 수 있음",
          mitigation: "seed/config preset과 run log export를 설계한다.",
          status: "open",
        },
      ],
      milestones: [
        {
          id: "m1-charter",
          week: "1-2",
          title: "Project charter and baseline scope",
          status: "planned",
          deliverables: ["연구 질문", "MVP 시나리오", "현재 Unity 구조 조사"],
        },
        {
          id: "m2-baseline-demo",
          week: "3-4",
          title: "Baseline simulation demo",
          status: "planned",
          deliverables: ["LLM provider config", "첫 내부 demo", "provider 비교 로그"],
        },
        {
          id: "m3-behavior",
          week: "5-6",
          title: "Persona and deception behavior study",
          status: "planned",
          deliverables: ["prompt experiment", "행동 관찰 노트", "observer UI 개선안"],
        },
        {
          id: "m4-midterm",
          week: "7-8",
          title: "Midterm presentation and edge cases",
          status: "planned",
          deliverables: ["edge case board", "중간 발표 deck", "demo media"],
        },
        {
          id: "m5-results",
          week: "9-10",
          title: "Repeated runs and result table",
          status: "planned",
          deliverables: ["실험 결과표", "비용/지연 비교", "최종 발표 narrative"],
        },
        {
          id: "m6-archive",
          week: "11-12",
          title: "Final presentation and archive",
          status: "planned",
          deliverables: ["final deck", "demo script", "retrospective", "archive page"],
        },
      ],
    },
  ],
  sessions: [
    {
      id: "session-charter",
      projectId: "mafia-simulation",
      date: "2026-06-15",
      title: "Kickoff and research framing",
      ownerId: "project-maintainer",
      status: "planned",
      agenda: ["연구 질문 확정", "Unity 코드 구조 리뷰", "12주 산출물 합의"],
      decisions: [],
      actionItems: ["MVP 시나리오 초안", "현재 스크립트별 책임 정리"],
    },
    {
      id: "session-provider-baseline",
      projectId: "mafia-simulation",
      date: "2026-06-29",
      title: "Provider baseline experiment",
      ownerId: "study-editor",
      status: "planned",
      agenda: ["provider config 점검", "JSON 안정성 측정", "latency 측정 기준 합의"],
      decisions: [],
      actionItems: ["OpenAI/Ollama/Claude run log 작성", "parse failure case 수집"],
    },
  ],
  tasks: [
    {
      id: "task-map-current-unity-flow",
      projectId: "mafia-simulation",
      milestoneId: "m1-charter",
      title: "GameManager, AgentController, TurnScheduler 책임 정리",
      ownerId: "study-editor",
      status: "todo",
      due: "2026-06-21",
      links: ["https://github.com/team-ASP/MafiaSimulation"],
    },
    {
      id: "task-provider-config-table",
      projectId: "mafia-simulation",
      milestoneId: "m2-baseline-demo",
      title: "LLM provider별 config와 응답 unpack 규칙 표준화",
      ownerId: "project-maintainer",
      status: "todo",
      due: "2026-07-05",
      links: [],
    },
    {
      id: "task-site-vercel-migration",
      projectId: "mafia-simulation",
      milestoneId: "m1-charter",
      title: "ASP Study Hub를 Vercel/Next.js 운영 구조로 전환",
      ownerId: "admin",
      status: "in-progress",
      due: "2026-06-23",
      links: ["https://vercel.com/docs/git/vercel-for-github"],
    },
  ],
  logs: [
    {
      id: "log-architecture-baseline",
      projectId: "mafia-simulation",
      date: "2026-06-15",
      type: "decision",
      authorId: "project-maintainer",
      title: "초기 아키텍처 관찰 포인트",
      summary:
        "GameManager가 phase 전환과 log event를 관리하고, AgentController가 기억과 개별 상호작용을 보유하며, TurnScheduler가 회의와 투표 순서를 담당한다.",
      relatedMilestoneId: "m1-charter",
      links: ["https://github.com/team-ASP/MafiaSimulation"],
    },
    {
      id: "log-hosting-policy",
      projectId: "mafia-simulation",
      date: "2026-06-16",
      type: "decision",
      authorId: "admin",
      title: "사이트 운영은 Vercel 기반 동적 구조를 목표로 한다",
      summary:
        "GitHub Pages는 public snapshot/fallback으로 두고, 로그인과 쓰기 권한은 Vercel server-side API에서 처리한다.",
      relatedMilestoneId: "m1-charter",
      links: ["https://vercel.com/docs/git"],
    },
  ],
  archive: [
    {
      id: "archive-mafia-simulation",
      projectId: "mafia-simulation",
      status: "draft",
      required: ["final summary", "demo video", "final deck", "repository", "retrospective"],
      missing: ["demo video", "final deck", "retrospective"],
    },
  ],
  reviewQueue: [
    {
      id: "review-auth-policy",
      title: "GitHub 로그인과 Editor 권한 정책",
      type: "policy",
      status: "ready-for-review",
      ownerId: "admin",
      target: "product-policies",
    },
    {
      id: "review-vercel-plan",
      title: "Vercel Preview/Production 배포 전략",
      type: "deployment",
      status: "ready-for-review",
      ownerId: "project-maintainer",
      target: "vercel-hosting-automation-plan",
    },
  ],
  comments: [
    {
      id: "comment-review-flow",
      scope: "project",
      targetId: "mafia-simulation",
      visibility: "team-only",
      authorId: "study-editor",
      createdAt: "2026-06-16",
      body: "세션 기록과 실험 로그는 빠르게 작성하되, archive 반영은 review queue를 통과시키는 흐름이 좋아 보입니다.",
    },
  ],
  auditEvents: [
    {
      id: "audit-initial-plan",
      actorId: "admin",
      action: "publish-policy-draft",
      targetId: "product-roadmap",
      createdAt: "2026-06-16",
      summary: "Vercel hosting, GitHub login, review queue 정책 초안을 추가했다.",
    },
  ],
  policies: {
    roles: [
      { role: "Viewer", permission: "공개 프로젝트, 로그, 아카이브 조회" },
      { role: "Developer", permission: "프로젝트 생성, 백로그와 기록 작성/수정/삭제, 리뷰와 아카이브 운영" },
      { role: "Admin", permission: "Developer 권한 전체와 정적 seed 콘텐츠 숨김, 감사 로그, 시스템 정책 관리" },
    ],
    deployment:
      "Vercel Git Integration을 우선 사용하고, 더 강한 release gate가 필요해지면 GitHub Actions controlled deploy로 확장한다.",
  },
};
