window.ASP_DATA = {
  team: {
    name: "title_mockA",
    org: "team-ASP",
    season: "season_mockA",
    tagline: "subtitle_mockA",
    description: "description_mockA",
    githubOrg: "https://github.com/team-ASP",
    stats: [
      { label: "stat_label_mockA", value: "stat_value_mockA", tone: "mint" },
      { label: "stat_label_mockB", value: "stat_value_mockB", tone: "blue" },
      { label: "stat_label_mockC", value: "stat_value_mockC", tone: "amber" },
      { label: "stat_label_mockD", value: "3", tone: "rose" },
    ],
  },
  nav: [
    { id: "dashboard", label: "nav_mockA", icon: "grid" },
    { id: "about", label: "nav_mockB", icon: "info" },
    { id: "notice", label: "nav_mockC", icon: "megaphone" },
    { id: "recruit", label: "nav_mockD", icon: "userPlus" },
    { id: "squad", label: "nav_mockE", icon: "users" },
    { id: "projects", label: "nav_mockF", icon: "folder" },
    { id: "events", label: "nav_mockG", icon: "calendar" },
    { id: "blog", label: "nav_mockH", icon: "file" },
    { id: "seasons", label: "nav_mockI", icon: "layers" },
    { id: "leaderboard", label: "nav_mockJ", icon: "chart" },
    { id: "achievements", label: "nav_mockK", icon: "award" },
    { id: "wiki", label: "nav_mockL", icon: "book" },
    { id: "profile", label: "nav_mockM", icon: "user" },
    { id: "admin", label: "nav_mockN", icon: "settings" },
  ],
  dashboard: {
    heroNodes: ["node_mockA", "node_mockB", "node_mockC", "node_mockD", "node_mockE"],
    quickActions: [
      { label: "button_mockA", target: "projects" },
      { label: "button_mockB", target: "events" },
      { label: "button_mockC", target: "wiki" },
    ],
  },
  projects: [
    {
      id: "project_mockA",
      title: "title_mockA",
      status: "status_mockA",
      category: "category_mockA",
      level: "level_mockA",
      description: "description_mockA",
      tags: ["tag_mockA", "tag_mockB", "tag_mockC"],
      members: "members_mockA",
      schedule: "schedule_mockA",
      progress: 32,
      owner: "owner_mockA",
    },
    {
      id: "project_mockB",
      title: "title_mockB",
      status: "status_mockB",
      category: "category_mockB",
      level: "level_mockB",
      description: "description_mockB",
      tags: ["tag_mockA", "tag_mockB", "tag_mockC"],
      members: "members_mockB",
      schedule: "schedule_mockB",
      progress: 64,
      owner: "owner_mockB",
    },
    {
      id: "project_mockC",
      title: "title_mockC",
      status: "status_mockC",
      category: "category_mockC",
      level: "level_mockC",
      description: "description_mockC",
      tags: ["tag_mockA", "tag_mockB", "tag_mockC"],
      members: "members_mockC",
      schedule: "schedule_mockC",
      progress: 78,
      owner: "owner_mockC",
    },
    {
      id: "project_mockD",
      title: "title_mockD",
      status: "status_mockD",
      category: "category_mockD",
      level: "level_mockD",
      description: "description_mockD",
      tags: ["tag_mockA", "tag_mockB", "tag_mockC"],
      members: "members_mockD",
      schedule: "schedule_mockD",
      progress: 12,
      owner: "owner_mockA",
    },
  ],
  events: [
    { id: "event_mockA", date: "date_mockA", title: "title_mockA", category: "category_mockA", mode: "mode_mockA", status: "status_mockA" },
    { id: "event_mockB", date: "date_mockB", title: "title_mockB", category: "category_mockB", mode: "mode_mockB", status: "status_mockB" },
    { id: "event_mockC", date: "date_mockC", title: "title_mockC", category: "category_mockC", mode: "mode_mockA", status: "status_mockC" },
    { id: "event_mockD", date: "date_mockD", title: "title_mockD", category: "category_mockD", mode: "mode_mockB", status: "status_mockA" },
  ],
  notices: [
    { id: "notice_mockA", title: "title_mockA", category: "category_mockA", date: "date_mockA", summary: "description_mockA" },
    { id: "notice_mockB", title: "title_mockB", category: "category_mockB", date: "date_mockB", summary: "description_mockB" },
    { id: "notice_mockC", title: "title_mockC", category: "category_mockC", date: "date_mockC", summary: "description_mockC" },
  ],
  blogPosts: [
    { id: "blog_mockA", title: "title_mockA", category: "category_mockA", author: "author_mockA", metric: "metric_mockA", summary: "description_mockA" },
    { id: "blog_mockB", title: "title_mockB", category: "category_mockB", author: "author_mockB", metric: "metric_mockB", summary: "description_mockB" },
    { id: "blog_mockC", title: "title_mockC", category: "category_mockC", author: "author_mockC", metric: "metric_mockC", summary: "description_mockC" },
    { id: "blog_mockD", title: "title_mockD", category: "category_mockD", author: "author_mockA", metric: "metric_mockD", summary: "description_mockD" },
  ],
  wikiPages: [
    { id: "wiki_mockA", title: "title_mockA", category: "category_mockA", updated: "updated_mockA", summary: "description_mockA" },
    { id: "wiki_mockB", title: "title_mockB", category: "category_mockB", updated: "updated_mockB", summary: "description_mockB" },
    { id: "wiki_mockC", title: "title_mockC", category: "category_mockC", updated: "updated_mockC", summary: "description_mockC" },
    { id: "wiki_mockD", title: "title_mockD", category: "category_mockD", updated: "updated_mockD", summary: "description_mockD" },
  ],
  squads: [
    { id: "squad_mockA", title: "title_mockA", category: "category_mockA", size: "size_mockA", description: "description_mockA", stack: ["stack_mockA", "stack_mockB"] },
    { id: "squad_mockB", title: "title_mockB", category: "category_mockB", size: "size_mockB", description: "description_mockB", stack: ["stack_mockA", "stack_mockC"] },
    { id: "squad_mockC", title: "title_mockC", category: "category_mockC", size: "size_mockC", description: "description_mockC", stack: ["stack_mockB", "stack_mockC"] },
  ],
  seasons: [
    { id: "season_mockA", title: "title_mockA", period: "period_mockA", status: "status_mockA", description: "description_mockA" },
    { id: "season_mockB", title: "title_mockB", period: "period_mockB", status: "status_mockB", description: "description_mockB" },
    { id: "season_mockC", title: "title_mockC", period: "period_mockC", status: "status_mockC", description: "description_mockC" },
  ],
  members: [
    { id: "member_mockA", name: "member_mockA", role: "role_mockA", focus: "focus_mockA", points: 0, github: "github_mockA" },
    { id: "member_mockB", name: "member_mockB", role: "role_mockB", focus: "focus_mockB", points: 0, github: "github_mockB" },
    { id: "member_mockC", name: "member_mockC", role: "role_mockC", focus: "focus_mockC", points: 0, github: "github_mockC" },
  ],
  badges: [
    { id: "badge_mockA", title: "title_mockA", description: "description_mockA", count: "count_mockA" },
    { id: "badge_mockB", title: "title_mockB", description: "description_mockB", count: "count_mockB" },
    { id: "badge_mockC", title: "title_mockC", description: "description_mockC", count: "count_mockC" },
    { id: "badge_mockD", title: "title_mockD", description: "description_mockD", count: "count_mockD" },
  ],
  recruitSteps: [
    { title: "title_mockA", description: "description_mockA" },
    { title: "title_mockB", description: "description_mockB" },
    { title: "title_mockC", description: "description_mockC" },
  ],
  adminTasks: [
    { title: "title_mockA", description: "description_mockA" },
    { title: "title_mockB", description: "description_mockB" },
    { title: "title_mockC", description: "description_mockC" },
    { title: "title_mockD", description: "description_mockD" },
  ],
};
